-- MySQL Script generated by MySQL Workbench
-- Fri May 22 04:15:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Роль`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Роль` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Пользователь`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Пользователь` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `фамилия` VARCHAR(100) NOT NULL,
  `имя` VARCHAR(100) NOT NULL,
  `отчество` VARCHAR(100) NULL,
  `логин` VARCHAR(45) NOT NULL,
  `пароль` VARCHAR(45) NOT NULL,
  `Роль_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id пользователя_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `логин_UNIQUE` (`логин` ASC) VISIBLE,
  INDEX `fk_Пользователь_Роль_idx` (`Роль_id` ASC) VISIBLE,
  CONSTRAINT `fk_Пользователь_Роль`
    FOREIGN KEY (`Роль_id`)
    REFERENCES `mydb`.`Роль` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Вид спорта`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Вид спорта` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `мировой рекорд` VARCHAR(45) NULL,
  `дата рекорда` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Страница`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Страница` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Право доступа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Право доступа` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Роль_id` INT NOT NULL,
  `Страница_id` INT NOT NULL,
  INDEX `fk_Право доступа_Роль1_idx` (`Роль_id` ASC) VISIBLE,
  INDEX `fk_Право доступа_Страница1_idx` (`Страница_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Право доступа_Роль1`
    FOREIGN KEY (`Роль_id`)
    REFERENCES `mydb`.`Роль` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Право доступа_Страница1`
    FOREIGN KEY (`Страница_id`)
    REFERENCES `mydb`.`Страница` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Тренер`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Тренер` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Право доступа_id` INT NOT NULL,
  `Пользователь_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Пользователь_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Тренер_Право доступа1_idx` (`Право доступа_id` ASC) VISIBLE,
  INDEX `fk_Тренер_Пользователь1_idx` (`Пользователь_id` ASC) VISIBLE,
  CONSTRAINT `fk_Тренер_Право доступа1`
    FOREIGN KEY (`Право доступа_id`)
    REFERENCES `mydb`.`Право доступа` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Тренер_Пользователь1`
    FOREIGN KEY (`Пользователь_id`)
    REFERENCES `mydb`.`Пользователь` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Команда`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Команда` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(45) NOT NULL,
  `Вид спорта_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Команда_Вид спорта1_idx` (`Вид спорта_id` ASC) VISIBLE,
  CONSTRAINT `fk_Команда_Вид спорта1`
    FOREIGN KEY (`Вид спорта_id`)
    REFERENCES `mydb`.`Вид спорта` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Спортсмен`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Спортсмен` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `дата рождения` DATE NOT NULL,
  `команда` VARCHAR(45) NULL,
  `спортивный разряд` VARCHAR(45) NULL,
  `Тренер_id` INT NOT NULL,
  `Команда_id` INT NOT NULL,
  `Право доступа_id` INT NOT NULL,
  `Пользователь_id` INT NOT NULL,
  UNIQUE INDEX `id спортсмена_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_Спортсмен_Тренер1_idx` (`Тренер_id` ASC) VISIBLE,
  INDEX `fk_Спортсмен_Команда1_idx` (`Команда_id` ASC) VISIBLE,
  INDEX `fk_Спортсмен_Право доступа1_idx` (`Право доступа_id` ASC) VISIBLE,
  INDEX `fk_Спортсмен_Пользователь1_idx` (`Пользователь_id` ASC) VISIBLE,
  CONSTRAINT `fk_Спортсмен_Тренер1`
    FOREIGN KEY (`Тренер_id`)
    REFERENCES `mydb`.`Тренер` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Спортсмен_Команда1`
    FOREIGN KEY (`Команда_id`)
    REFERENCES `mydb`.`Команда` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Спортсмен_Право доступа1`
    FOREIGN KEY (`Право доступа_id`)
    REFERENCES `mydb`.`Право доступа` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Спортсмен_Пользователь1`
    FOREIGN KEY (`Пользователь_id`)
    REFERENCES `mydb`.`Пользователь` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Судья`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Судья` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Право доступа_id` INT NOT NULL,
  `Пользователь_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Судья_Право доступа1_idx` (`Право доступа_id` ASC) VISIBLE,
  INDEX `fk_Судья_Пользователь1_idx` (`Пользователь_id` ASC) VISIBLE,
  CONSTRAINT `fk_Судья_Право доступа1`
    FOREIGN KEY (`Право доступа_id`)
    REFERENCES `mydb`.`Право доступа` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Судья_Пользователь1`
    FOREIGN KEY (`Пользователь_id`)
    REFERENCES `mydb`.`Пользователь` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Соревнование`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Соревнование` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Вид спорта_id` INT NOT NULL,
  `название` VARCHAR(100) NOT NULL,
  `дата` DATE NULL,
  `Судья_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Соревнование_Вид спорта1_idx` (`Вид спорта_id` ASC) VISIBLE,
  INDEX `fk_Соревнование_Судья1_idx` (`Судья_id` ASC) VISIBLE,
  CONSTRAINT `fk_Соревнование_Вид спорта1`
    FOREIGN KEY (`Вид спорта_id`)
    REFERENCES `mydb`.`Вид спорта` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Соревнование_Судья1`
    FOREIGN KEY (`Судья_id`)
    REFERENCES `mydb`.`Судья` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Результат соревнования`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Результат соревнования` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Соревнование_id` INT NOT NULL,
  `Спортсмен_id` INT NOT NULL,
  `Команда спортсменов_id` INT NOT NULL,
  `Результат` VARCHAR(45) NULL,
  `Место` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Результат соревнования_Спортс_idx` (`Спортсмен_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Результат соревнования_Соревно1`
    FOREIGN KEY (`Соревнование_id`)
    REFERENCES `mydb`.`Соревнование` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Результат соревнования_Спортсм1`
    FOREIGN KEY (`Спортсмен_id`)
    REFERENCES `mydb`.`Спортсмен` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Упражнение`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Упражнение` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Название` VARCHAR(45) NULL,
  `Описание` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Тренировка`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Тренировка` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Тренер_id` INT NOT NULL,
  `Спортсмен_id` INT NOT NULL,
  INDEX `fk_Программа тренировки спортсме_idx1` (`Тренер_id` ASC) VISIBLE,
  INDEX `fk_Программа тренировки спортсме_idx2` (`Спортсмен_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Программа тренировки спортсмен2`
    FOREIGN KEY (`Тренер_id`)
    REFERENCES `mydb`.`Тренер` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Программа тренировки спортсмен3`
    FOREIGN KEY (`Спортсмен_id`)
    REFERENCES `mydb`.`Спортсмен` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Программа тренировки`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Программа тренировки` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Упражнение_id` INT NOT NULL,
  `Тренировка_id` INT NOT NULL,
  `Кол-во раз` VARCHAR(45) NULL,
  `Время выполнения` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Упражнение_idx` (`Упражнение_id` ASC) VISIBLE,
  INDEX `fk_Связь_Программа тренировки1_idx` (`Тренировка_id` ASC) VISIBLE,
  CONSTRAINT `Упражнение_id`
    FOREIGN KEY (`Упражнение_id`)
    REFERENCES `mydb`.`Упражнение` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Тренировка_id`
    FOREIGN KEY (`Тренировка_id`)
    REFERENCES `mydb`.`Тренировка` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Продукт`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Продукт` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Количество каллорий` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Норма каллорий`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Норма каллорий` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Кол-во каллорий в день` INT NOT NULL,
  `Продукт_id` INT NOT NULL,
  `Спортсмен_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Норма каллорий_Продукт1_idx` (`Продукт_id` ASC) VISIBLE,
  INDEX `fk_Норма каллорий_Спортсмен1_idx` (`Спортсмен_id` ASC) VISIBLE,
  CONSTRAINT `fk_Норма каллорий_Продукт1`
    FOREIGN KEY (`Продукт_id`)
    REFERENCES `mydb`.`Продукт` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Норма каллорий_Спортсмен1`
    FOREIGN KEY (`Спортсмен_id`)
    REFERENCES `mydb`.`Спортсмен` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Питание`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Питание` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Желаемый вес` INT NULL,
  `Кол-во каллорий в день` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Программа контроля веса спортсмена`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Программа контроля веса спортсмена` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Питание_id` INT NOT NULL,
  `Спортсмен_id` INT NOT NULL,
  `Тренер_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `Питание_id_idx` (`Питание_id` ASC) VISIBLE,
  INDEX `Спортсмен_id_idx` (`Спортсмен_id` ASC) VISIBLE,
  INDEX `Тренер_id_idx` (`Тренер_id` ASC) VISIBLE,
  CONSTRAINT `Питание_id`
    FOREIGN KEY (`Питание_id`)
    REFERENCES `mydb`.`Питание` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Спортсмен_id`
    FOREIGN KEY (`Спортсмен_id`)
    REFERENCES `mydb`.`Спортсмен` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Тренер_id`
    FOREIGN KEY (`Тренер_id`)
    REFERENCES `mydb`.`Тренер` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
